name: snakevcf
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - pandas=2.3.0 
  - snakemake=9.5.1 
  - bcftools
  - cyvcf2
  - vcftools=0.1.17
  - plink=1.90b7.7
  - beagle=5.4
  - samtools=1.21
  - bedtools=2.31.1

