---
temp_dir: "scratch/"       # will be removed in the end. Store your intermediate files her
keep_temp_dir: true  # if true, the temp directory will be kept at the end of the run
result_dir: "results/"     # will be kept.

threads: 20                # number of threads to use

# Sample file: one per line
# Format: # sample_name  [tab]  vcf_file
# Example:
# sample    vcf
# vfaba_raw	vcf_files/test.vcf.gz
samples: config/samples.tsv # tab-separated file with VCF file(s) and associated short names

# optional tsv file with individuals to keep;
# one column with individuals, one individual per line (no header)
# write "all" to keep all individuals
individuals: config/individuals.tsv # has to end with .tsv


# vcftools parameters
vcftools:
  snp: 
    max_missing_fraction_per_snp_site: "0.2" # max fraction of missing genotypes (lower than or equal to; <=)

# bcftools parameters: 
# First filters: parameters for filtering on SNP sites (common for all individuals)
# Second filters: parameters for each genotype (on all or a subset of individuals)
bcftools:
  snp: 
    min_snp_quality:                     "30" # QUAL field
    min_snp_depth:                       "5" # minimum depth of coverage  per SNP site(lower than or equal to; <=)
    mean_depth_per_snp_site:             "10" # mean depth of coverage per SNP site (lower than or equal to; <=)
  individuals:
    min_ind_depth:                       "5"    # minimum depth of coverage per sample (lower than or equal to; <=)
    min_genotype_quality:                "30"   # minimum genotype quality (lower than or equal to; <=)
    min_maf_before_imputation:           "0.01" # minimum minor allele frequency (higher than or equal to; >=) before imputation
    min_maf_after_imputation:            "0.05" # minimum minor allele frequency (higher than or equal to; >=) after imputation
    max_missing_fraction_per_genotype:   "0.1"  # max fraction of missing genotype calls (lower than or equal to; <=) 
    max_heterozygosity:                  "0.15" # max fraction of heterozygous genotypes (depending on the reproduction mode: allogamous or autogamous)

# Beagle v5 parameters:
beagle: 
  memory: "4G" # memory for Beagle (e.g. 4G, 8G, 16G, etc.)
  impute: true # if true, Beagle will be used to impute missing genotypes







